---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-infra-net
  namespace: quick-infra-net
spec:
  selector:
    matchLabels:
      app: quick-infra-net
  replicas: 2
  template:
    metadata:
      labels:
        app: quick-infra-net
    spec:
      containers:
      - name: nginx
        image: quick-infra-k8s-nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      #nginx-exporter is necessary for monitoring nginx container on k8s
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.11.0
        args:
          - --nginx.scrape-uri=http://localhost:80/stub_status
        ports:
          - containerPort: 9113
            name: metrics
      - name: php-fpm
        image: quick-infra-k8s-php-fpm:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000