---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-infra-net
  namespace: quick-infra-net
spec:
  selector:
    matchLabels:
      app: quick-infra-net
  replicas: 2
  template:
    metadata:
      labels:
        app: quick-infra-net
    spec:
      containers:
      - name: nginx
        image: quick-infra-k8s-nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      #nginx-exporter is necessary for monitoring nginx container on k8s
      - name: nginx-exporter
        image: 'nginx/nginx-prometheus-exporter:1.3.0'
        args:
          - '-nginx.scrape-uri=http://quick-infra.net:9113/nginx_status'
        ports:
          - containerPort: 9113
            name: metrics
      #php-fpm-exporter is necessary for monitoring php-fpm container on k8s      
      - name: php-fpm
        image: quick-infra-k8s-php-fpm:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000